from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── FundingAgency ──────────────────────────────────────
        migrations.CreateModel(
            name='FundingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_type', models.CharField(max_length=20, choices=[
                    ('GOVERNMENT','Government'),('PRIVATE','Private'),
                    ('INTERNATIONAL','International'),('INDUSTRY','Industry'),
                    ('NGO','NGO'),('OTHER','Other'),
                ])),
                ('country', models.CharField(default='India', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['name'], 'verbose_name': 'Funding Agency'},
        ),

        # ── ResearchArea ───────────────────────────────────────
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_areas', to='globals.discipline')),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_areas', to='research_procedures.researcharea')),
                ('faculty_experts', models.ManyToManyField(blank=True, related_name='expertise_areas', to='globals.faculty')),
            ],
            options={'ordering': ['name'], 'verbose_name': 'Research Area'},
        ),

        # ── ResearchGroup ──────────────────────────────────────
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_groups', to='globals.discipline')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='globals.faculty')),
                ('members', models.ManyToManyField(blank=True, related_name='research_groups', to='globals.faculty')),
                ('faculty_under_group', models.ManyToManyField(blank=True, related_name='allfaculty', to=settings.AUTH_USER_MODEL)),
                ('students_under_group', models.ManyToManyField(blank=True, related_name='allstudents', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['name'], 'verbose_name_plural': 'Research Groups'},
        ),

        # ── SponsoredProject ───────────────────────────────────
        migrations.CreateModel(
            name='SponsoredProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('sanction_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('extended_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('PROPOSED','Proposed'),('SUBMITTED','Submitted'),('UNDER_REVIEW','Under Review'),
                    ('APPROVED','Approved'),('SANCTIONED','Sanctioned'),('ONGOING','Ongoing'),
                    ('EXTENDED','Extended'),('COMPLETED','Completed'),('TERMINATED','Terminated'),('REJECTED','Rejected'),
                ], default='PROPOSED', max_length=20)),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='rspc/projects/proposals/')),
                ('sanction_letter', models.FileField(blank=True, null=True, upload_to='rspc/projects/sanctions/')),
                ('completion_report', models.FileField(blank=True, null=True, upload_to='rspc/projects/completion/')),
                ('pf_no', models.IntegerField(blank=True, null=True)),
                ('ptype', models.CharField(blank=True, default='Research', max_length=100, null=True)),
                ('pi', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('co_pi', models.CharField(blank=True, default=' ', max_length=1500, null=True)),
                ('financial_outlay', models.CharField(blank=True, default=' ', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_entry', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_submission', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='research_procedures.fundingagency')),
                ('principal_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pi_projects', to='globals.faculty')),
                ('research_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_projects', to='research_procedures.researcharea')),
                ('research_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_projects', to='research_procedures.researchgroup')),
                ('co_principal_investigators', models.ManyToManyField(blank=True, related_name='copi_projects', to='globals.faculty')),
                ('research_scholars', models.ManyToManyField(blank=True, related_name='sponsored_projects', to='globals.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at'], 'verbose_name': 'Sponsored Project'},
        ),

        # ── ProjectExpenditure ─────────────────────────────────
        migrations.CreateModel(
            name='ProjectExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('expenditure_head', models.CharField(max_length=20, choices=[
                    ('MANPOWER','Manpower/Salary'),('EQUIPMENT','Equipment'),('CONSUMABLES','Consumables'),
                    ('TRAVEL','Travel'),('PUBLICATIONS','Publications'),('CONTINGENCY','Contingency'),
                    ('OVERHEAD','Overhead'),('SERVICES','Services'),('OTHER','Other'),
                ])),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_document', models.FileField(blank=True, null=True, upload_to='rspc/projects/bills/')),
                ('status', models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected')], default='PENDING', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='research_procedures.sponsoredproject')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenditures', to='globals.extrainfo')),
            ],
            options={'ordering': ['-date'], 'verbose_name': 'Project Expenditure'},
        ),

        # ── ProjectMilestone ───────────────────────────────────
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING','Pending'),('IN_PROGRESS','In Progress'),('COMPLETED','Completed'),('DELAYED','Delayed')], default='PENDING', max_length=20)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('deliverable_file', models.FileField(blank=True, null=True, upload_to='rspc/projects/deliverables/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='research_procedures.sponsoredproject')),
            ],
            options={'ordering': ['due_date'], 'verbose_name': 'Project Milestone'},
        ),

        # ── ProjectReport ──────────────────────────────────────
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=20, choices=[
                    ('QUARTERLY','Quarterly'),('HALF_YEARLY','Half Yearly'),('ANNUAL','Annual'),
                    ('FINAL','Final'),('UTILIZATION','Utilization Certificate'),
                ])),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('summary', models.TextField()),
                ('achievements', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(upload_to='rspc/projects/reports/')),
                ('status', models.CharField(choices=[('DRAFT','Draft'),('SUBMITTED','Submitted'),('APPROVED','Approved'),('REJECTED','Rejected')], default='DRAFT', max_length=20)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='research_procedures.sponsoredproject')),
            ],
            options={'ordering': ['-period_from'], 'verbose_name': 'Project Report'},
        ),

        # ── ConsultancyProject ─────────────────────────────────
        migrations.CreateModel(
            name='ConsultancyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('project_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_type', models.CharField(blank=True, max_length=50, null=True, choices=[
                    ('INDUSTRY','Industry'),('GOVERNMENT','Government'),('NGO','NGO'),
                    ('ACADEMIC','Academic'),('INDIVIDUAL','Individual'),('OTHER','Other'),
                ])),
                ('client_contact', models.TextField(blank=True, null=True)),
                ('client_email', models.EmailField(blank=True, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('consultants', models.CharField(blank=True, max_length=150, null=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('faculty_share', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('institute_share', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('financial_outlay', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[
                    ('PROPOSED','Proposed'),('NEGOTIATION','Under Negotiation'),('APPROVED','Approved'),
                    ('ONGOING','Ongoing'),('COMPLETED','Completed'),('CANCELLED','Cancelled'),
                ], default='PROPOSED', max_length=20)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='rspc/consultancy/agreements/')),
                ('completion_certificate', models.FileField(blank=True, null=True, upload_to='rspc/consultancy/certificates/')),
                ('pf_no', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_entry', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultancies', to='globals.faculty')),
                ('co_consultants', models.ManyToManyField(blank=True, related_name='co_consultancies', to='globals.faculty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at'], 'verbose_name': 'Consultancy Project'},
        ),

        # ── Publication ────────────────────────────────────────
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('publication_type', models.CharField(max_length=20, choices=[
                    ('JOURNAL','Journal Article'),('CONFERENCE','Conference Paper'),('BOOK','Book'),
                    ('BOOK_CHAPTER','Book Chapter'),('PATENT','Patent'),('THESIS','Thesis'),
                    ('TECHNICAL_REPORT','Technical Report'),('PREPRINT','Preprint'),('OTHER','Other'),
                ])),
                ('external_authors', models.TextField(blank=True, null=True)),
                ('journal_conference_name', models.CharField(max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('issue', models.CharField(blank=True, max_length=20, null=True)),
                ('pages', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('index_type', models.CharField(choices=[
                    ('SCI','SCI'),('SCIE','SCIE'),('SCOPUS','Scopus'),('WOS','Web of Science'),
                    ('UGC_CARE','UGC Care List'),('ABDC','ABDC'),('OTHER_INDEXED','Other Indexed'),('NONE','Non-indexed'),
                ], default='NONE', max_length=20)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='rspc/publications/')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='research_procedures.sponsoredproject')),
                ('faculty_authors', models.ManyToManyField(blank=True, related_name='publications', to='globals.faculty')),
                ('student_authors', models.ManyToManyField(blank=True, related_name='publications', to='globals.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_publications', to='globals.extrainfo')),
            ],
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Publication'},
        ),

        # ── Patent ─────────────────────────────────────────────
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('ipd_form_file', models.TextField(blank=True, null=True)),
                ('project_details_file', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('patent_type', models.CharField(choices=[
                    ('NATIONAL','National'),('INTERNATIONAL','International'),
                    ('PCT','PCT'),('DESIGN','Design'),('TRADEMARK','Trademark'),
                ], default='NATIONAL', max_length=20)),
                ('external_inventors', models.TextField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('publication_number', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('grant_number', models.CharField(blank=True, max_length=50, null=True)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('DRAFT','Draft'),('FILED','Filed'),('PUBLISHED','Published'),
                    ('UNDER_EXAMINATION','Under Examination'),('GRANTED','Granted'),
                    ('REJECTED','Rejected'),('LAPSED','Lapsed'),('ABANDONED','Abandoned'),
                ], default='DRAFT', max_length=20)),
                ('country', models.CharField(default='India', max_length=50)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('specification_document', models.FileField(blank=True, null=True, upload_to='rspc/patents/specs/')),
                ('grant_certificate', models.FileField(blank=True, null=True, upload_to='rspc/patents/certificates/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents_legacy', to='globals.extrainfo')),
                ('faculty_inventors', models.ManyToManyField(blank=True, related_name='patents', to='globals.faculty')),
                ('student_inventors', models.ManyToManyField(blank=True, related_name='patents', to='globals.student')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patents_new', to='research_procedures.sponsoredproject')),
            ],
            options={'ordering': ['-filing_date'], 'verbose_name': 'Patent'},
        ),

        # ── ResearchScholar ────────────────────────────────────
        migrations.CreateModel(
            name='ResearchScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('fellowship_type', models.CharField(blank=True, max_length=50, null=True, choices=[
                    ('GATE','GATE'),('NET','NET'),('CSIR','CSIR'),('DBT','DBT'),
                    ('INSTITUTE','Institute'),('SPONSORED','Sponsored'),('SELF_FUNDED','Self Funded'),('OTHER','Other'),
                ])),
                ('fellowship_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fellowship_start_date', models.DateField(blank=True, null=True)),
                ('fellowship_end_date', models.DateField(blank=True, null=True)),
                ('progress_status', models.CharField(choices=[
                    ('REGISTERED','Registered'),('COURSEWORK','Coursework'),
                    ('COMPREHENSIVE_EXAM','Comprehensive Exam'),('SYNOPSIS_PHASE','Synopsis Phase'),
                    ('RESEARCH_PHASE','Research Phase'),('THESIS_WRITING','Thesis Writing'),
                    ('DEFENSE_READY','Defense Ready'),('DEFENDED','Defended'),('COMPLETED','Completed'),
                ], default='REGISTERED', max_length=20)),
                ('coursework_completed', models.BooleanField(default=False)),
                ('coursework_completion_date', models.DateField(blank=True, null=True)),
                ('comprehensive_exam_passed', models.BooleanField(default=False)),
                ('comprehensive_exam_date', models.DateField(blank=True, null=True)),
                ('comprehensive_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('synopsis_submitted', models.BooleanField(default=False)),
                ('synopsis_date', models.DateField(blank=True, null=True)),
                ('synopsis_approved', models.BooleanField(default=False)),
                ('synopsis_approval_date', models.DateField(blank=True, null=True)),
                ('thesis_submitted', models.BooleanField(default=False)),
                ('thesis_submission_date', models.DateField(blank=True, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=500, null=True)),
                ('defense_date', models.DateField(blank=True, null=True)),
                ('defense_result', models.CharField(blank=True, choices=[('PASS','Pass'),('REVISIONS_REQUIRED','Revisions Required'),('FAIL','Fail')], max_length=50, null=True)),
                ('degree_awarded_date', models.DateField(blank=True, null=True)),
                ('publications_count', models.IntegerField(default=0)),
                ('patents_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_scholar_info', to='globals.student')),
            ],
            options={'verbose_name': 'Research Scholar'},
        ),

        # ── TechTransfer ───────────────────────────────────────
        migrations.CreateModel(
            name='TechTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pf_no', models.IntegerField()),
                ('details', models.CharField(default=' ', max_length=500)),
                ('date_entry', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # ── ResearchProject (legacy) ───────────────────────────
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pf_no', models.IntegerField()),
                ('ptype', models.CharField(default='Research', max_length=100)),
                ('pi', models.CharField(default=' ', max_length=1000)),
                ('co_pi', models.CharField(default=' ', max_length=1500)),
                ('title', models.TextField(default=' ', max_length=5000)),
                ('funding_agency', models.CharField(default=' ', max_length=250, null=True)),
                ('financial_outlay', models.CharField(default=' ', max_length=150, null=True)),
                ('status', models.CharField(choices=[('Awarded','Awarded'),('Submitted','Submitted'),('Ongoing','Ongoing'),('Completed','Completed')], default='Proposed', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('date_submission', models.DateField(blank=True, null=True)),
                ('date_entry', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
