# Generated by Django 4.2.13 on 2026-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancyproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consultancy Project', 'verbose_name_plural': 'Consultancy Projects'},
        ),
        migrations.AlterModelOptions(
            name='fundingagency',
            options={'ordering': ['name'], 'verbose_name': 'Funding Agency', 'verbose_name_plural': 'Funding Agencies'},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ['-filing_date'], 'verbose_name': 'Patent', 'verbose_name_plural': 'Patents'},
        ),
        migrations.AlterModelOptions(
            name='projectexpenditure',
            options={'ordering': ['-date'], 'verbose_name': 'Project Expenditure', 'verbose_name_plural': 'Project Expenditures'},
        ),
        migrations.AlterModelOptions(
            name='projectmilestone',
            options={'ordering': ['due_date'], 'verbose_name': 'Project Milestone', 'verbose_name_plural': 'Project Milestones'},
        ),
        migrations.AlterModelOptions(
            name='projectreport',
            options={'ordering': ['-period_from'], 'verbose_name': 'Project Report', 'verbose_name_plural': 'Project Reports'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='researcharea',
            options={'ordering': ['name'], 'verbose_name': 'Research Area', 'verbose_name_plural': 'Research Areas'},
        ),
        migrations.AlterModelOptions(
            name='researchscholar',
            options={'verbose_name': 'Research Scholar', 'verbose_name_plural': 'Research Scholars'},
        ),
        migrations.AlterModelOptions(
            name='sponsoredproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sponsored Project', 'verbose_name_plural': 'Sponsored Projects'},
        ),
        migrations.AddField(
            model_name='patent',
            name='ipd_form',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patent',
            name='project_details',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='consultancyproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundingagency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectexpenditure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsoredproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='techtransfer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='consultancyproject',
            index=models.Index(fields=['project_number'], name='research_pr_project_97c4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='consultancyproject',
            index=models.Index(fields=['status'], name='research_pr_status_35cc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingagency',
            index=models.Index(fields=['name'], name='research_pr_name_65ecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingagency',
            index=models.Index(fields=['agency_type'], name='research_pr_agency__1b6d48_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['application_number'], name='research_pr_applica_56ede2_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['status'], name='research_pr_status_fcdc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['filing_date'], name='research_pr_filing__2b7d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpenditure',
            index=models.Index(fields=['project', 'date'], name='research_pr_project_2cb96d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpenditure',
            index=models.Index(fields=['status'], name='research_pr_status_87655b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'due_date'], name='research_pr_project_3d396b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['status'], name='research_pr_status_66cd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreport',
            index=models.Index(fields=['project', 'period_from'], name='research_pr_project_09d273_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreport',
            index=models.Index(fields=['status'], name='research_pr_status_bb68e6_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['doi'], name='research_pr_doi_ded3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['year'], name='research_pr_year_de3e17_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type'], name='research_pr_publica_5b5e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='researcharea',
            index=models.Index(fields=['name'], name='research_pr_name_2f206b_idx'),
        ),
        migrations.AddIndex(
            model_name='researcharea',
            index=models.Index(fields=['is_active'], name='research_pr_is_acti_4e5dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroup',
            index=models.Index(fields=['name'], name='research_pr_name_7b6332_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroup',
            index=models.Index(fields=['is_active'], name='research_pr_is_acti_bb2355_idx'),
        ),
        migrations.AddIndex(
            model_name='researchscholar',
            index=models.Index(fields=['progress_status'], name='research_pr_progres_625637_idx'),
        ),
        migrations.AddIndex(
            model_name='researchscholar',
            index=models.Index(fields=['enrollment_date'], name='research_pr_enrollm_174295_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsoredproject',
            index=models.Index(fields=['project_number'], name='research_pr_project_c82a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsoredproject',
            index=models.Index(fields=['status'], name='research_pr_status_2951c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsoredproject',
            index=models.Index(fields=['created_at'], name='research_pr_created_9c10cb_idx'),
        ),
    ]
