# Generated by Django 4.2.13 on 2026-03-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0001_initial"),
        ("research_procedures", "0002_alter_consultancyproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexpenditure",
            name="last_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PatentStatusNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="globals.extrainfo",
                    ),
                ),
                (
                    "patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_notifications",
                        to="research_procedures.patent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
