# Generated by Django 4.2.13 on 2026-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_procedures", "0004_alter_sponsoredproject_status_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancyproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PROPOSED", "Proposed"),
                    ("SUBMITTED", "Submitted for Verification"),
                    ("VERIFIED_BY_ADMIN", "Verified by Admin"),
                    ("NEGOTIATION", "Under Negotiation"),
                    ("APPROVED", "Approved"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PROPOSED",
                max_length=20,
            ),
        ),
    ]
