# Generated by Django 3.1.5 on 2026-04-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20241020_1126'),
        ('research_procedures', '0005_alter_consultancyproject_status'),
    ]

    operations = [
    ]
